services:
    railtours:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8083:80
    directus:
        image: directus/directus:11.1.0
        ports:
            - 8057:8055
        volumes:
            - ./database:/directus/database
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        environment:
            SECRET: "T&|A~1)9!V8.R+:o#C:&ZB[hT0&J;F"
            ADMIN_EMAIL: "admin@example.com"
            ADMIN_PASSWORD: "purple"
            DB_CLIENT: "sqlite3"
            DB_FILENAME: "/directus/database/data.db"
            WEBSOCKETS_ENABLED: "true"
            CACHE_ENABLED: 'true'
            CACHE_STORE: 'redis'
            CACHE_AUTO_PURGE: "true"
            REDIS: 'redis://cache:6379'
            CONTENT_SECURITY_POLICY_DIRECTIVES__UPGRADE_INSECURE_REQUESTS: 'null'
            CORS_ENABLED: "true"
            CORS_ORIGIN: "true"
    cache:
        image: redis:6
        restart: always




